In [3]:
import pandas as pd

import numpy as np

import matplotlib as mlp

import matplotlib.pyplot as plt

import seaborn as sns

df1 = pd.read_csv("2008-2009-H.csv")

In [25]:
df2 = pd.read_csv("2009-2010-H.csv")

In [32]:
df3 = pd.read_csv("2010-2011-H.csv")

In [40]:
df4 = pd.read_csv("2011-2012-H.csv")

In [45]:
df5 = pd.read_csv("2012-2013-H.csv")

In [49]:
df6 = pd.read_csv("2013-2014-H.csv")

In [51]:
df7 = pd.read_csv("2014-2015-H.csv")

In [58]:
df8 = pd.read_csv("2015-2016-H.csv")
df9 = pd.read_csv("2016-2017-H.csv")
df10 = pd.read_csv("2017-2018-H.csv")
df11 = pd.read_csv("2018-2019-H.csv")
df12 = pd.read_csv("2019-2020-H.csv")
df13 = pd.read_csv("2020-2021-H.csv")
df14 = pd.read_csv("2021-2022-H.csv")

In [20]:
df1.drop("HART", axis=1)

,playerId,season,name,team,position,situation,games_played,icetime,shifts,gameScore,...,OffIce_F_xGoals,OffIce_A_xGoals,OffIce_F_shotAttempts,OffIce_A_shotAttempts,xGoalsForAfterShifts,xGoalsAgainstAfterShifts,corsiForAfterShifts,corsiAgainstAfterShifts,fenwickForAfterShifts,fenwickAgainstAfterShifts
0,8462196,2008,Stephane Robidas,DAL,D,other,72,6729,105,31.93,...,6.79,12.11,106,122,0.14,0.00,4,0,3,0
1,8462196,2008,Stephane Robidas,DAL,D,all,72,105958,2026,31.71,...,95.61,116.39,2161,2223,0.00,0.00,0,0,0,0
2,8462196,2008,Stephane Robidas,DAL,D,5on5,72,74053,1480,31.71,...,66.29,74.66,1678,1647,3.64,0.18,91,10,74,8
3,8462196,2008,Stephane Robidas,DAL,D,4on5,72,10397,235,30.26,...,2.24,27.37,57,380,0.15,0.00,3,0,3,0
4,8462196,2008,Stephane Robidas,DAL,D,5on4,72,14779,206,31.69,...,19.15,1.47,294,42,0.13,0.00,6,0,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4420,8470622,2008,Patrick Eaves,CAR,R,other,74,988,24,8.52,...,7.03,6.09,64,73,0.00,0.00,0,0,0,0
4421,8470622,2008,Patrick Eaves,CAR,R,all,74,49916,1220,22.75,...,189.43,174.29,3830,3361,0.00,0.00,0,0,0,0
4422,8470622,2008,Patrick Eaves,CAR,R,5on5,74,41058,950,22.75,...,110.64,108.53,2666,2443,1.10,0.76,43,28,33,25
4423,8470622,2008,Patrick Eaves,CAR,R,4on5,74,6636,188,22.18,...,4.08,32.28,59,514,0.15,0.04,1,1,1,1
4424,8470622,2008,Patrick Eaves,CAR,R,5on4,74,1234,58,12.36,...,25.44,3.71,450,68,0.00,0.00,1,0,0,0

In [21]:
names = ["Alex Ovechkin", "Evgeni Malkin", "Pavel Datsyuk"]

df1.loc[df1['name'].isin(names), 'HART'] = 1 
df1.loc[~df1['name'].isin(names), 'HART'] = 0

In [22]:
df1

,playerId,season,name,team,position,situation,games_played,icetime,shifts,gameScore,...,OffIce_A_xGoals,OffIce_F_shotAttempts,OffIce_A_shotAttempts,xGoalsForAfterShifts,xGoalsAgainstAfterShifts,corsiForAfterShifts,corsiAgainstAfterShifts,fenwickForAfterShifts,fenwickAgainstAfterShifts,HART
0,8462196,2008,Stephane Robidas,DAL,D,other,72,6729,105,31.93,...,12.11,106,122,0.14,0.00,4,0,3,0,0
1,8462196,2008,Stephane Robidas,DAL,D,all,72,105958,2026,31.71,...,116.39,2161,2223,0.00,0.00,0,0,0,0,0
2,8462196,2008,Stephane Robidas,DAL,D,5on5,72,74053,1480,31.71,...,74.66,1678,1647,3.64,0.18,91,10,74,8,0
3,8462196,2008,Stephane Robidas,DAL,D,4on5,72,10397,235,30.26,...,27.37,57,380,0.15,0.00,3,0,3,0,0
4,8462196,2008,Stephane Robidas,DAL,D,5on4,72,14779,206,31.69,...,1.47,294,42,0.13,0.00,6,0,6,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4420,8470622,2008,Patrick Eaves,CAR,R,other,74,988,24,8.52,...,6.09,64,73,0.00,0.00,0,0,0,0,0
4421,8470622,2008,Patrick Eaves,CAR,R,all,74,49916,1220,22.75,...,174.29,3830,3361,0.00,0.00,0,0,0,0,0
4422,8470622,2008,Patrick Eaves,CAR,R,5on5,74,41058,950,22.75,...,108.53,2666,2443,1.10,0.76,43,28,33,25,0
4423,8470622,2008,Patrick Eaves,CAR,R,4on5,74,6636,188,22.18,...,32.28,59,514,0.15,0.04,1,1,1,1,0
4424,8470622,2008,Patrick Eaves,CAR,R,5on4,74,1234,58,12.36,...,3.71,450,68,0.00,0.00,1,0,0,0,0

In [23]:
df1.loc[df1['name'].isin(names)]

,playerId,season,name,team,position,situation,games_played,icetime,shifts,gameScore,...,OffIce_A_xGoals,OffIce_F_shotAttempts,OffIce_A_shotAttempts,xGoalsForAfterShifts,xGoalsAgainstAfterShifts,corsiForAfterShifts,corsiAgainstAfterShifts,fenwickForAfterShifts,fenwickAgainstAfterShifts,HART
1115,8471214,2008,Alex Ovechkin,WSH,L,other,79,5714,91,130.30,...,12.44,112,191,0.02,0.00,2,0,1,0,1
1116,8471214,2008,Alex Ovechkin,WSH,L,all,79,109042,1694,139.29,...,140.20,2477,2886,0.00,0.00,0,0,0,0,1
1117,8471214,2008,Alex Ovechkin,WSH,L,5on5,79,75344,1280,139.29,...,76.73,2203,1927,1.59,1.68,29,46,23,36,1
1118,8471214,2008,Alex Ovechkin,WSH,L,4on5,79,4359,137,114.69,...,43.34,82,626,0.00,0.00,0,0,0,0,1
1119,8471214,2008,Alex Ovechkin,WSH,L,5on4,79,23625,186,139.29,...,0.51,53,13,0.00,0.17,0,3,0,3,1
2570,8467514,2008,Pavel Datsyuk,DET,C,other,80,5450,93,98.59,...,12.28,158,146,0.21,0.06,4,1,3,1,1
2571,8467514,2008,Pavel Datsyuk,DET,C,all,80,92224,2000,113.74,...,149.46,3194,2673,0.00,0.00,0,0,0,0,1
2572,8467514,2008,Pavel Datsyuk,DET,C,5on5,80,65522,1416,113.74,...,95.42,2486,1949,2.21,1.91,38,27,35,24,1
2573,8467514,2008,Pavel Datsyuk,DET,C,4on5,80,6956,214,105.93,...,34.69,66,501,0.51,0.25,2,3,2,2,1
2574,8467514,2008,Pavel Datsyuk,DET,C,5on4,80,14296,277,113.74,...,1.73,470,38,0.06,0.03,2,1,2,1,1
3410,8471215,2008,Evgeni Malkin,PIT,C,other,82,6946,105,83.54,...,13.17,84,184,0.00,0.02,0,2,0,1,1
3411,8471215,2008,Evgeni Malkin,PIT,C,all,82,110784,1945,97.33,...,145.63,2449,3177,0.00,0.00,0,0,0,0,1
3412,8471215,2008,Evgeni Malkin,PIT,C,5on5,82,74345,1476,97.33,...,83.19,2131,2213,1.07,2.49,28,80,21,62,1
3413,8471215,2008,Evgeni Malkin,PIT,C,4on5,82,5021,152,84.70,...,42.92,70,637,0.00,0.01,0,3,0,2,1
3414,8471215,2008,Evgeni Malkin,PIT,C,5on4,82,24472,212,97.33,...,1.23,134,31,0.03,0.02,1,2,1,1,1

In [24]:
df1

,playerId,season,name,team,position,situation,games_played,icetime,shifts,gameScore,...,OffIce_A_xGoals,OffIce_F_shotAttempts,OffIce_A_shotAttempts,xGoalsForAfterShifts,xGoalsAgainstAfterShifts,corsiForAfterShifts,corsiAgainstAfterShifts,fenwickForAfterShifts,fenwickAgainstAfterShifts,HART
0,8462196,2008,Stephane Robidas,DAL,D,other,72,6729,105,31.93,...,12.11,106,122,0.14,0.00,4,0,3,0,0
1,8462196,2008,Stephane Robidas,DAL,D,all,72,105958,2026,31.71,...,116.39,2161,2223,0.00,0.00,0,0,0,0,0
2,8462196,2008,Stephane Robidas,DAL,D,5on5,72,74053,1480,31.71,...,74.66,1678,1647,3.64,0.18,91,10,74,8,0
3,8462196,2008,Stephane Robidas,DAL,D,4on5,72,10397,235,30.26,...,27.37,57,380,0.15,0.00,3,0,3,0,0
4,8462196,2008,Stephane Robidas,DAL,D,5on4,72,14779,206,31.69,...,1.47,294,42,0.13,0.00,6,0,6,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4420,8470622,2008,Patrick Eaves,CAR,R,other,74,988,24,8.52,...,6.09,64,73,0.00,0.00,0,0,0,0,0
4421,8470622,2008,Patrick Eaves,CAR,R,all,74,49916,1220,22.75,...,174.29,3830,3361,0.00,0.00,0,0,0,0,0
4422,8470622,2008,Patrick Eaves,CAR,R,5on5,74,41058,950,22.75,...,108.53,2666,2443,1.10,0.76,43,28,33,25,0
4423,8470622,2008,Patrick Eaves,CAR,R,4on5,74,6636,188,22.18,...,32.28,59,514,0.15,0.04,1,1,1,1,0
4424,8470622,2008,Patrick Eaves,CAR,R,5on4,74,1234,58,12.36,...,3.71,450,68,0.00,0.00,1,0,0,0,0

In [6]:
player_id = []

df1

,playerId,season,name,team,position,situation,games_played,icetime,shifts,gameScore,...,OffIce_A_xGoals,OffIce_F_shotAttempts,OffIce_A_shotAttempts,xGoalsForAfterShifts,xGoalsAgainstAfterShifts,corsiForAfterShifts,corsiAgainstAfterShifts,fenwickForAfterShifts,fenwickAgainstAfterShifts,HART
0,8462196,2008,Stephane Robidas,DAL,D,other,72,6729,105,31.93,...,12.11,106,122,0.14,0.00,4,0,3,0,
1,8462196,2008,Stephane Robidas,DAL,D,all,72,105958,2026,31.71,...,116.39,2161,2223,0.00,0.00,0,0,0,0,
2,8462196,2008,Stephane Robidas,DAL,D,5on5,72,74053,1480,31.71,...,74.66,1678,1647,3.64,0.18,91,10,74,8,
3,8462196,2008,Stephane Robidas,DAL,D,4on5,72,10397,235,30.26,...,27.37,57,380,0.15,0.00,3,0,3,0,
4,8462196,2008,Stephane Robidas,DAL,D,5on4,72,14779,206,31.69,...,1.47,294,42,0.13,0.00,6,0,6,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4420,8470622,2008,Patrick Eaves,CAR,R,other,74,988,24,8.52,...,6.09,64,73,0.00,0.00,0,0,0,0,
4421,8470622,2008,Patrick Eaves,CAR,R,all,74,49916,1220,22.75,...,174.29,3830,3361,0.00,0.00,0,0,0,0,
4422,8470622,2008,Patrick Eaves,CAR,R,5on5,74,41058,950,22.75,...,108.53,2666,2443,1.10,0.76,43,28,33,25,
4423,8470622,2008,Patrick Eaves,CAR,R,4on5,74,6636,188,22.18,...,32.28,59,514,0.15,0.04,1,1,1,1,
4424,8470622,2008,Patrick Eaves,CAR,R,5on4,74,1234,58,12.36,...,3.71,450,68,0.00,0.00,1,0,0,0,

In [26]:
df2

,playerId,season,name,team,position,situation,games_played,icetime,shifts,gameScore,...,OffIce_F_xGoals,OffIce_A_xGoals,OffIce_F_shotAttempts,OffIce_A_shotAttempts,xGoalsForAfterShifts,xGoalsAgainstAfterShifts,corsiForAfterShifts,corsiAgainstAfterShifts,fenwickForAfterShifts,fenwickAgainstAfterShifts
0,8471707,2009,James Neal,DAL,R,other,77,3599,74,33.57,...,13.68,9.37,153,142,0.00,0.00,0,0,0,0
1,8471707,2009,James Neal,DAL,R,all,77,84185,1813,50.74,...,136.81,151.60,2887,3259,0.00,0.00,0,0,0,0
2,8471707,2009,James Neal,DAL,R,5on5,77,64419,1385,50.74,...,89.79,94.77,2201,2382,0.94,2.14,35,48,27,41
3,8471707,2009,James Neal,DAL,R,4on5,77,4212,133,41.45,...,2.24,29.32,47,508,0.01,0.02,1,1,1,1
4,8471707,2009,James Neal,DAL,R,5on4,77,11955,221,50.13,...,25.97,3.20,427,62,0.24,0.10,2,3,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4390,8471675,2009,Sidney Crosby,PIT,C,other,80,6307,106,98.50,...,9.79,11.17,101,157,0.00,0.12,0,5,0,3
4391,8471675,2009,Sidney Crosby,PIT,C,all,80,105401,1876,116.70,...,122.00,142.66,2628,3040,0.00,0.00,0,0,0,0
4392,8471675,2009,Sidney Crosby,PIT,C,5on5,80,72074,1405,116.70,...,95.06,87.81,2229,2182,0.70,2.30,26,58,21,48
4393,8471675,2009,Sidney Crosby,PIT,C,4on5,80,4112,156,97.36,...,4.25,35.00,92,591,0.00,0.00,0,0,0,0
4394,8471675,2009,Sidney Crosby,PIT,C,5on4,80,22908,209,117.00,...,11.64,1.35,185,25,0.39,0.35,3,8,3,6

In [28]:
names = ["Alex Ovechkin", "Henrik Sedin", "Sidney Crosby"]

df2.loc[df2['name'].isin(names), 'HART'] = 1 
df2.loc[~df2['name'].isin(names), 'HART'] = 0

In [31]:
df2["HART"] = df2["HART"].astype(int)

In [33]:
df3

,playerId,season,name,team,position,situation,games_played,icetime,shifts,gameScore,...,OffIce_F_xGoals,OffIce_A_xGoals,OffIce_F_shotAttempts,OffIce_A_shotAttempts,xGoalsForAfterShifts,xGoalsAgainstAfterShifts,corsiForAfterShifts,corsiAgainstAfterShifts,fenwickForAfterShifts,fenwickAgainstAfterShifts
0,8470144,2010,Frans Nielsen,NYI,C,other,71,2884,62,38.23,...,13.51,14.39,150,130,0.00,0.00,0,0,0,0
1,8470144,2010,Frans Nielsen,NYI,C,all,71,75672,1692,48.22,...,131.32,158.11,2675,3171,0.00,0.00,0,0,0,0
2,8470144,2010,Frans Nielsen,NYI,C,5on5,71,50658,1130,48.22,...,86.94,112.55,2089,2607,1.58,2.15,43,46,35,38
3,8470144,2010,Frans Nielsen,NYI,C,4on5,71,11891,313,48.22,...,3.99,22.73,58,338,0.03,0.06,2,4,2,2
4,8470144,2010,Frans Nielsen,NYI,C,5on4,71,10239,187,46.30,...,23.17,3.50,333,61,0.19,0.00,3,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4450,8462077,2010,Jochen Hecht,BUF,C,other,67,2382,49,31.83,...,10.70,15.63,116,148,0.20,0.05,2,2,2,1
4451,8462077,2010,Jochen Hecht,BUF,C,all,67,68658,1530,42.49,...,128.02,135.44,2703,2774,0.00,0.00,0,0,0,0
4452,8462077,2010,Jochen Hecht,BUF,C,5on5,67,53175,1159,42.49,...,85.42,86.33,2039,2106,3.37,2.76,45,46,39,37
4453,8462077,2010,Jochen Hecht,BUF,C,4on5,67,7620,202,41.60,...,2.21,23.21,39,389,0.01,0.01,2,1,1,1
4454,8462077,2010,Jochen Hecht,BUF,C,5on4,67,5481,120,33.28,...,20.59,3.55,404,57,0.00,0.00,0,0,0,0

In [42]:


df4.loc[df4['name'].isin(names), 'HART'] = 1 
df4.loc[~df4['name'].isin(names), 'HART'] = 0

In [44]:
df4["HART"] = df4["HART"].astype(int)

In [47]:
df4[df4['HART'] == 1]

,playerId,season,name,team,position,situation,games_played,icetime,shifts,gameScore,...,OffIce_A_xGoals,OffIce_F_shotAttempts,OffIce_A_shotAttempts,xGoalsForAfterShifts,xGoalsAgainstAfterShifts,corsiForAfterShifts,corsiAgainstAfterShifts,fenwickForAfterShifts,fenwickAgainstAfterShifts,HART
200,8471215,2011,Evgeni Malkin,PIT,C,other,75,5215,80,107.81,...,11.49,99,145,0.03,0.00,1,0,1,0,1
201,8471215,2011,Evgeni Malkin,PIT,C,all,75,94507,1644,124.27,...,125.59,2592,2685,0.00,0.00,0,0,0,0,1
202,8471215,2011,Evgeni Malkin,PIT,C,5on5,75,70805,1387,124.27,...,83.29,2272,2007,1.23,2.26,29,43,24,36,1
203,8471215,2011,Evgeni Malkin,PIT,C,4on5,75,184,25,34.37,...,10.62,39,188,0.00,0.00,0,0,0,0,1
204,8471215,2011,Evgeni Malkin,PIT,C,5on4,75,18303,152,120.56,...,0.99,116,19,0.41,0.20,2,2,2,2,1
875,8474564,2011,Steven Stamkos,T.B,C,other,82,5217,97,70.48,...,9.13,71,142,0.01,0.08,1,3,1,3,1
876,8474564,2011,Steven Stamkos,T.B,C,all,82,108192,2017,94.52,...,159.11,2328,3268,0.00,0.00,0,0,0,0,1
877,8474564,2011,Steven Stamkos,T.B,C,5on5,82,83403,1643,94.52,...,98.92,2052,2391,1.27,2.17,30,54,26,42,1
878,8474564,2011,Steven Stamkos,T.B,C,4on5,82,2578,97,70.54,...,37.69,41,518,0.00,0.00,0,0,0,0,1
879,8474564,2011,Steven Stamkos,T.B,C,5on4,82,16994,180,92.54,...,1.04,127,31,0.13,0.26,1,4,1,4,1

In [46]:
df5

,playerId,season,name,team,position,situation,games_played,icetime,shifts,gameScore,...,OffIce_F_xGoals,OffIce_A_xGoals,OffIce_F_shotAttempts,OffIce_A_shotAttempts,xGoalsForAfterShifts,xGoalsAgainstAfterShifts,corsiForAfterShifts,corsiAgainstAfterShifts,fenwickForAfterShifts,fenwickAgainstAfterShifts
0,8475793,2012,Ryan Johansen,CBJ,C,other,40,1089,27,4.80,...,5.90,8.19,76,81,0.04,0.00,1,0,1,0
1,8475793,2012,Ryan Johansen,CBJ,C,all,40,38602,843,9.35,...,60.38,70.45,1417,1643,0.00,0.00,0,0,0,0
2,8475793,2012,Ryan Johansen,CBJ,C,5on5,40,32025,702,9.35,...,38.83,48.60,1105,1255,1.11,0.61,17,20,11,14
3,8475793,2012,Ryan Johansen,CBJ,C,4on5,40,308,24,3.43,...,1.97,5.12,23,134,0.00,0.00,0,0,0,0
4,8475793,2012,Ryan Johansen,CBJ,C,5on4,40,5180,90,8.19,...,9.16,1.16,141,19,0.12,0.00,2,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4190,8473446,2012,Erik Johnson,COL,D,other,31,1527,33,10.88,...,4.40,7.07,53,60,0.00,0.07,0,1,0,1
4191,8473446,2012,Erik Johnson,COL,D,all,31,38602,876,9.00,...,46.79,56.21,1101,1197,0.00,0.00,0,0,0,0
4192,8473446,2012,Erik Johnson,COL,D,5on5,31,29710,671,9.00,...,35.14,37.51,889,904,1.51,0.10,55,8,39,5
4193,8473446,2012,Erik Johnson,COL,D,4on5,31,4180,110,7.05,...,0.96,10.27,23,197,0.03,0.00,2,0,2,0
4194,8473446,2012,Erik Johnson,COL,D,5on4,31,3185,62,8.75,...,5.91,0.89,123,17,0.00,0.00,1,0,0,0

In [54]:
df6["HART"] = df6["HART"].astype(int)

In [55]:
df7

,playerId,season,name,team,position,situation,games_played,icetime,shifts,gameScore,...,OffIce_F_xGoals,OffIce_A_xGoals,OffIce_F_shotAttempts,OffIce_A_shotAttempts,xGoalsForAfterShifts,xGoalsAgainstAfterShifts,corsiForAfterShifts,corsiAgainstAfterShifts,fenwickForAfterShifts,fenwickAgainstAfterShifts
0,8475793,2014,Ryan Johansen,CBJ,C,other,82,5202,94,53.11,...,8.99,10.64,102,147,0.00,0.20,0,1,0,1
1,8475793,2014,Ryan Johansen,CBJ,C,all,82,95951,2064,58.64,...,119.30,155.82,2663,3268,0.00,0.00,0,0,0,0
2,8475793,2014,Ryan Johansen,CBJ,C,5on5,82,71236,1507,58.64,...,89.13,100.06,2206,2464,2.17,1.11,37,43,29,35
3,8475793,2014,Ryan Johansen,CBJ,C,4on5,82,6240,261,52.24,...,4.11,40.94,70,583,0.00,0.13,0,2,0,2
4,8475793,2014,Ryan Johansen,CBJ,C,5on4,82,13273,202,55.28,...,14.08,0.79,258,23,0.01,0.00,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4405,8468535,2014,Antoine Vermette,CHI,C,other,82,3362,66,23.56,...,8.15,9.09,91,106,0.00,0.02,0,1,0,1
4406,8468535,2014,Antoine Vermette,CHI,C,all,82,87782,2010,28.50,...,139.88,160.58,3309,3414,0.00,0.00,0,0,0,0
4407,8468535,2014,Antoine Vermette,CHI,C,5on5,82,67229,1567,28.50,...,102.36,111.92,2761,2658,1.78,1.72,48,49,38,39
4408,8468535,2014,Antoine Vermette,CHI,C,4on5,82,6607,197,27.22,...,2.74,26.81,51,454,0.00,0.00,0,0,0,0
4409,8468535,2014,Antoine Vermette,CHI,C,5on4,82,10584,180,27.47,...,20.11,2.50,321,49,0.02,0.00,2,1,2,1

In [56]:
names = ["Carey Price", "Alex Ovechkin", "John Tavares"]

df7.loc[df7['name'].isin(names), 'HART'] = 1 
df7.loc[~df7['name'].isin(names), 'HART'] = 0

In [59]:
df7["HART"] = df7["HART"].astype(int)

In [60]:
names = ["Patrick Kane", "Sidney Crosby", "Jamie Benn"]

df8.loc[df8['name'].isin(names), 'HART'] = 1 
df8.loc[~df8['name'].isin(names), 'HART'] = 0

In [61]:
df8["HART"] = df8["HART"].astype(int)

In [62]:
names = ["Connor McDavid", "Sidney Crosby", "Sergei Bobrovsky"]

df9.loc[df9['name'].isin(names), 'HART'] = 1 
df9.loc[~df9['name'].isin(names), 'HART'] = 0

In [64]:
df9["HART"] = df9["HART"].astype(int)

In [67]:
names = ["Taylor Hall", "Nathan MacKinnon", "Anze Kopitar"]

df10.loc[df10['name'].isin(names), 'HART'] = 1 
df10.loc[~df10['name'].isin(names), 'HART'] = 0

In [68]:
df10["HART"] = df10["HART"].astype(int)

In [71]:
names = ["Nikita Kucherov", "Sidney Crosby", "Connor McDavid"]

df11.loc[df11['name'].isin(names), 'HART'] = 1 
df11.loc[~df11['name'].isin(names), 'HART'] = 0

In [72]:
df11["HART"] = df11["HART"].astype(int)

In [73]:
names = ["Leon Draisaitl", "Nathan MacKinnon", "Artemi Panarin"]

df12.loc[df12['name'].isin(names), 'HART'] = 1 
df12.loc[~df12['name'].isin(names), 'HART'] = 0

In [74]:
df12["HART"] = df12["HART"].astype(int)

In [75]:
names = ["Connor McDavid", "Auston Matthews", "Nathan MacKinnon"]

df13.loc[df13['name'].isin(names), 'HART'] = 1 
df13.loc[~df13['name'].isin(names), 'HART'] = 0

In [76]:
df13["HART"] = df13["HART"].astype(int)

In [77]:
names = ["Connor McDavid", "Auston Matthews", "Igor Shesterkin"]

df14.loc[df14['name'].isin(names), 'HART'] = 1 
df14.loc[~df14['name'].isin(names), 'HART'] = 0

In [78]:
df14["HART"] = df14["HART"].astype(int)

In [79]:
final_set = df1.append(df2)

In [82]:
added_dfs = [df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14]

In [83]:
final_set2 = df1.append(added_dfs)

In [85]:
final_set2.to_csv("final_set.csv")